#!/usr/bin/env bash

set -e

# Platform-specific VS Code settings path
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  VSCODE_CONFIG_PATH="$HOME/.config/Code/User"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  VSCODE_CONFIG_PATH="$HOME/Library/Application Support/Code/User"
elif [[ "$OSTYPE" == "msys" ]]; then
  VSCODE_CONFIG_PATH="$APPDATA\\Code\\User"
else
  echo "Unsupported OS"
  exit 1
fi

# Copy your custom keybindings
mkdir -pv "$VSCODE_CONFIG_PATH"
ln -svf $PWD/keybindings.json "$VSCODE_CONFIG_PATH/keybindings.json"
ln -svf $PWD/settings.json "$VSCODE_CONFIG_PATH/settings.json"

echo "✅ VS Code keybindings and settings installed to $VSCODE_CONFIG_PATH"
